name: Discord Commits
description: Send commit summary to Discord using custom formatting
branding:
  icon: bell
  color: purple
inputs:
  webhook:
    description: discord webhook url without /github
    required: true
  message:
    description: "A general message that is displayed for all commits. Defaults to the repo name."
  last-commit-only:
    description: "Boolean - only show the last commit."

runs:
  using: node16
  main: dist/index.js