name: Entry

on:
  workflow_run:
    workflows:
      - Discord
      - Discord Copy
    types:
      - completed

jobs:
  disord_test_message:
    runs-on: ubuntu-latest
    name: discord commits
    steps:
      - name: Checkout
        uses: actions/checkout@v3
